### ISSUE TITLE
How did you get the marketplace is for AltStore pal?

### ISSUE THREAD

**Issue by JMcrafter26** [Michael-128/qBitControl-releases#1]

**Comment by Michael-128** [comment]
You have to contact AltStore directly if you want to publish an app https://altstore.io

**Comment by JMcrafter26** [comment]
And how does it work? Do they give you some sort of certificate or do they enable the source url? Or how do they do it?

**Comment by Michael-128** [comment]
I'm sure AltStore team will explain everything. You need to have your app notarized by apple, create a source, etc.

**Comment by JMcrafter26** [comment]
Ok thank you!

**Comment by Michael-128** [comment]
No problem! Good luck with publishing your app :)
